[2021-11-01 20:25:41] [INFO] [conftest.py line:30]->>开始清理截图和日志文件...
[2021-11-01 20:25:41] [INFO] [clear.py line:19]->>开始清理截图
[2021-11-01 20:25:41] [INFO] [clear.py line:30]->>清除截图完成
[2021-11-01 20:25:41] [INFO] [clear.py line:45]->>开始清理log
[2021-11-01 20:25:41] [INFO] [clear.py line:55]->>log清理完成
[2021-11-01 20:25:41] [INFO] [reader.py line:43]->>加载文件:/Users/mac/Desktop/my_code/WebFramework/data/login_data.yaml
[2021-11-01 20:25:41] [INFO] [reader.py line:43]->>加载文件:/Users/mac/Desktop/my_code/WebFramework/data/login_data.yaml
[2021-11-01 20:25:41] [INFO] [conftest.py line:63]->>*************** 开始执行用例：test01_login ***************
[2021-11-01 20:25:41] [INFO] [browser.py line:107]->>打开chrome浏览器
[2021-11-01 20:25:44] [INFO] [basepage.py line:49]->>导航到:https://maitenghuicai.com/login.html
[2021-11-01 20:25:45] [INFO] [basepage.py line:64]->>定位元素：('xpath', '//input[@name="accounts"]'), 元素描述：LoginPageRsrc.LOC_用户名框
[2021-11-01 20:25:45] [ERROR] [basepage.py line:69]->>元素定位失败,开始截图!
[2021-11-01 20:25:45] [ERROR] [basepage.py line:203]->>截屏失败
[2021-11-01 20:25:45] [ERROR] [logs.py line:60]->>test01_login(*args: tuple = (<testcases.test01_login.TestLogin object at 0x7fc776295250>,), **kwargs: dict = {'driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="6be435c16f6365068fb0aca23e2e3f44")>, 'arg': ['mik', 123456, '登录成功']})
Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 66, in find_element
    ele = WebDriverWait(self.driver, self._timeout).until(EC.visibility_of_element_located(locator.value))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/utils/logs.py", line 51, in wrap_func
    func(*args, **kwargs)
  File "/Users/mac/Desktop/my_code/WebFramework/testcases/test01_login.py", line 34, in test01_login
    res = page.login_result(arg[0], arg[1])
  File "/Users/mac/Desktop/my_code/WebFramework/pom/common_login.py", line 14, in login_result
    return self.login_page_obj.login(user, passwd)
  File "/Users/mac/Desktop/my_code/WebFramework/page/loginpage.py", line 21, in login
    self.find_element_and_send_keys(self.LoginPageRsrc.LOC_用户名框, user)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 232, in find_element_and_send_keys
    ele = self.find_element(locator)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 70, in find_element
    self.save_screenshot()
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 198, in save_screenshot
    self.driver.save_screenshot(filepath)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)

[2021-11-01 20:25:49] [INFO] [conftest.py line:55]->>关闭浏览器,并重置driver
[2021-11-01 20:25:49] [INFO] [conftest.py line:65]->>*************** 结束执行用例：test01_login ***************
[2021-11-01 20:25:49] [INFO] [conftest.py line:63]->>*************** 开始执行用例：test01_login ***************
[2021-11-01 20:25:49] [INFO] [browser.py line:107]->>打开chrome浏览器
[2021-11-01 20:25:52] [INFO] [basepage.py line:49]->>导航到:https://maitenghuicai.com/login.html
[2021-11-01 20:25:52] [INFO] [basepage.py line:64]->>定位元素：('xpath', '//input[@name="accounts"]'), 元素描述：LoginPageRsrc.LOC_用户名框
[2021-11-01 20:25:52] [ERROR] [basepage.py line:69]->>元素定位失败,开始截图!
[2021-11-01 20:25:52] [ERROR] [basepage.py line:203]->>截屏失败
[2021-11-01 20:25:52] [ERROR] [logs.py line:60]->>test01_login(*args: tuple = (<testcases.test01_login.TestLogin object at 0x7fc776295450>,), **kwargs: dict = {'driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="4ab314c16d2d1537292a861604cf70cf")>, 'arg': ['mik', 'abc123456', '密码错误']})
Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 66, in find_element
    ele = WebDriverWait(self.driver, self._timeout).until(EC.visibility_of_element_located(locator.value))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/utils/logs.py", line 51, in wrap_func
    func(*args, **kwargs)
  File "/Users/mac/Desktop/my_code/WebFramework/testcases/test01_login.py", line 34, in test01_login
    res = page.login_result(arg[0], arg[1])
  File "/Users/mac/Desktop/my_code/WebFramework/pom/common_login.py", line 14, in login_result
    return self.login_page_obj.login(user, passwd)
  File "/Users/mac/Desktop/my_code/WebFramework/page/loginpage.py", line 21, in login
    self.find_element_and_send_keys(self.LoginPageRsrc.LOC_用户名框, user)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 232, in find_element_and_send_keys
    ele = self.find_element(locator)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 70, in find_element
    self.save_screenshot()
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 198, in save_screenshot
    self.driver.save_screenshot(filepath)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)

[2021-11-01 20:25:56] [INFO] [conftest.py line:55]->>关闭浏览器,并重置driver
[2021-11-01 20:25:56] [INFO] [conftest.py line:65]->>*************** 结束执行用例：test01_login ***************
[2021-11-01 20:25:56] [INFO] [conftest.py line:63]->>*************** 开始执行用例：test01_login ***************
[2021-11-01 20:25:56] [INFO] [browser.py line:107]->>打开chrome浏览器
[2021-11-01 20:25:58] [INFO] [basepage.py line:49]->>导航到:https://maitenghuicai.com/login.html
[2021-11-01 20:25:59] [INFO] [basepage.py line:64]->>定位元素：('xpath', '//input[@name="accounts"]'), 元素描述：LoginPageRsrc.LOC_用户名框
[2021-11-01 20:25:59] [ERROR] [basepage.py line:69]->>元素定位失败,开始截图!
[2021-11-01 20:25:59] [ERROR] [basepage.py line:203]->>截屏失败
[2021-11-01 20:25:59] [ERROR] [logs.py line:60]->>test01_login(*args: tuple = (<testcases.test01_login.TestLogin object at 0x7fc776430d50>,), **kwargs: dict = {'driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="2fce655aaba62580c54da68c849a64c3")>, 'arg': ['mik2232', 123456, '登录帐号不存在']})
Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 66, in find_element
    ele = WebDriverWait(self.driver, self._timeout).until(EC.visibility_of_element_located(locator.value))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/utils/logs.py", line 51, in wrap_func
    func(*args, **kwargs)
  File "/Users/mac/Desktop/my_code/WebFramework/testcases/test01_login.py", line 34, in test01_login
    res = page.login_result(arg[0], arg[1])
  File "/Users/mac/Desktop/my_code/WebFramework/pom/common_login.py", line 14, in login_result
    return self.login_page_obj.login(user, passwd)
  File "/Users/mac/Desktop/my_code/WebFramework/page/loginpage.py", line 21, in login
    self.find_element_and_send_keys(self.LoginPageRsrc.LOC_用户名框, user)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 232, in find_element_and_send_keys
    ele = self.find_element(locator)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 70, in find_element
    self.save_screenshot()
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 198, in save_screenshot
    self.driver.save_screenshot(filepath)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=95.0.4638.69)

[2021-11-01 20:26:02] [INFO] [conftest.py line:55]->>关闭浏览器,并重置driver
[2021-11-01 20:26:02] [INFO] [conftest.py line:65]->>*************** 结束执行用例：test01_login ***************
[2021-11-01 20:26:02] [INFO] [conftest.py line:63]->>*************** 开始执行用例：test01_add_address ***************
[2021-11-01 20:26:02] [INFO] [browser.py line:107]->>打开chrome浏览器
[2021-11-01 20:26:05] [INFO] [reader.py line:43]->>加载文件:/Users/mac/Desktop/my_code/WebFramework/data/user_address_info_data.yaml
[2021-11-01 20:26:05] [INFO] [basepage.py line:49]->>导航到:https://maitenghuicai.com/login.html
[2021-11-01 20:26:06] [INFO] [basepage.py line:64]->>定位元素：('xpath', '//input[@name="accounts"]'), 元素描述：LoginPageRsrc.LOC_用户名框
[2021-11-01 20:26:06] [ERROR] [basepage.py line:69]->>元素定位失败,开始截图!
[2021-11-01 20:26:06] [ERROR] [basepage.py line:203]->>截屏失败
[2021-11-01 20:26:06] [ERROR] [logs.py line:60]->>test01_add_address(*args: tuple = (<testcases.test02_change_user_address.TestAddress object at 0x7fc7766ba490>,), **kwargs: dict = {'driver': <selenium.webdriver.chrome.webdriver.WebDriver (session="39447424846af1cbed6731afc03aaeea")>})
Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 66, in find_element
    ele = WebDriverWait(self.driver, self._timeout).until(EC.visibility_of_element_located(locator.value))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=95.0.4638.69)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/my_code/WebFramework/utils/logs.py", line 51, in wrap_func
    func(*args, **kwargs)
  File "/Users/mac/Desktop/my_code/WebFramework/testcases/test02_change_user_address.py", line 31, in test01_add_address
    self.address_info[3])
  File "/Users/mac/Desktop/my_code/WebFramework/pom/change_user_address.py", line 20, in add_address_form_homopage
    self.login_page_obj.login(self.user_info[0], self.user_info[1])
  File "/Users/mac/Desktop/my_code/WebFramework/page/loginpage.py", line 21, in login
    self.find_element_and_send_keys(self.LoginPageRsrc.LOC_用户名框, user)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 232, in find_element_and_send_keys
    ele = self.find_element(locator)
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 70, in find_element
    self.save_screenshot()
  File "/Users/mac/Desktop/my_code/WebFramework/common/basepage.py", line 198, in save_screenshot
    self.driver.save_screenshot(filepath)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mac/Desktop/my_code/WebFramework/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=95.0.4638.69)

[2021-11-01 20:26:09] [INFO] [conftest.py line:55]->>关闭浏览器,并重置driver
[2021-11-01 20:26:09] [INFO] [conftest.py line:65]->>*************** 结束执行用例：test01_add_address ***************
